<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Zone;
use App\Models\Locality;
use Illuminate\Support\Facades\DB;

class LocalitySeeder extends Seeder
{
    public function run(): void
    {
        $localities = [
            ['name' => 'Bo. El Siete', 'municipality_id' => '1'],
            ['name' => 'Col. Brisas Del Norte', 'municipality_id' => '1'],
            ['name' => 'Col. Club De Leones', 'municipality_id' => '1'],
            ['name' => 'Col. El Confite', 'municipality_id' => '1'],
            ['name' => 'Col. Irias Navas', 'municipality_id' => '1'],
            ['name' => 'Col. La Esperanza', 'municipality_id' => '1'],
            ['name' => 'Col. Lomas De Palmira', 'municipality_id' => '1'],
            ['name' => 'Col. Miramontes', 'municipality_id' => '1'],
            ['name' => 'Col. Modesto Rodas Alvarado', 'municipality_id' => '1'],
            ['name' => 'Col. Palmira', 'municipality_id' => '1'],
            ['name' => 'Col. 1 De Mayo', 'municipality_id' => '1'],
            ['name' => 'Col. 15 De Septiembre', 'municipality_id' => '1'],
            ['name' => 'Col. Roberto Padilla', 'municipality_id' => '1'],
            ['name' => 'Col. San Martin', 'municipality_id' => '1'],
            ['name' => 'Col. Altos De Sinai', 'municipality_id' => '1'],
            ['name' => 'Col. Armenia Bonito', 'municipality_id' => '1'],
            ['name' => 'Col. Brisas Del Caribe', 'municipality_id' => '1'],
            ['name' => 'Col. Bufalo', 'municipality_id' => '1'],
            ['name' => 'Col. Coco Pando', 'municipality_id' => '1'],
            ['name' => 'Col. El Dantillo', 'municipality_id' => '1'],
            ['name' => 'Col. Sochimilco O Goloson', 'municipality_id' => '1'],
            ['name' => 'Col. Las Delicias', 'municipality_id' => '1'],
            ['name' => 'Col. Las Delicias No. 2', 'municipality_id' => '1'],
            ['name' => 'Col. Piñera O Monte Cristo', 'municipality_id' => '1'],
            ['name' => 'Col. Menonita', 'municipality_id' => '1'],
            ['name' => 'Col. Ponce I Etapa', 'municipality_id' => '1'],
            ['name' => 'Col. Quinta San Fernando', 'municipality_id' => '1'],
            ['name' => 'Col. Riveras Del Caribe', 'municipality_id' => '1'],
            ['name' => 'Col. Sitraleyde', 'municipality_id' => '1'],
            ['name' => 'Col. Yessenia Castillo', 'municipality_id' => '1'],
            ['name' => 'Col. 26 De Junio', 'municipality_id' => '1'],
            ['name' => 'Col. Ponce II Etapa', 'municipality_id' => '1'],
            ['name' => 'Col. Trejo', 'municipality_id' => '1'],
            ['name' => 'Col. Gracias A Dios', 'municipality_id' => '1'],
            ['name' => 'Col. La Borda Del Curla', 'municipality_id' => '1'],
            ['name' => 'Col. Parcelamineto El Naranjito', 'municipality_id' => '1'],
            ['name' => 'Col. Bajos De Palmira', 'municipality_id' => '1'],
            ['name' => 'Col. Brisas Del Mar', 'municipality_id' => '1'],
            ['name' => 'Col. Barahona', 'municipality_id' => '1'],
            ['name' => 'Col. Angel Salinas', 'municipality_id' => '1'],
            ['name' => 'Col. Brisas Del Atlantico', 'municipality_id' => '1'],
            ['name' => 'Col. Villas Del Oeste', 'municipality_id' => '1'],
            ['name' => 'Col. Las Flores', 'municipality_id' => '1'],
            ['name' => 'Col. Universidad', 'municipality_id' => '1'],
            ['name' => 'Col. Goloson', 'municipality_id' => '1'],
            ['name' => 'Col. Altos De Miramontes', 'municipality_id' => '1'],
            ['name' => 'Col. Nueva Era', 'municipality_id' => '1'],
            ['name' => 'Col. Bautista', 'municipality_id' => '1'],
            ['name' => 'Col. Cerrato Palmira', 'municipality_id' => '1'],
            ['name' => 'Col. Olimpica', 'municipality_id' => '1'],
            ['name' => 'Villa Napoles', 'municipality_id' => '1'],
            ['name' => 'Col. Milagro De Dios', 'municipality_id' => '1'],
            ['name' => 'Col. Bonitillo', 'municipality_id' => '1'],
            ['name' => 'Col. La Victoria', 'municipality_id' => '1'],
            ['name' => 'Res. Marisol', 'municipality_id' => '1'],
            ['name' => 'Res. Vista Al Mar', 'municipality_id' => '1'],
            ['name' => 'Res. Villas Del Sol', 'municipality_id' => '1'],
            ['name' => 'Res. San Gabriel', 'municipality_id' => '1'],
            ['name' => 'Res. Casa Blanca', 'municipality_id' => '1'],
            ['name' => 'Res. Villa Romana', 'municipality_id' => '1'],
            ['name' => 'Res. Santa Marta', 'municipality_id' => '1'],
            ['name' => 'Tr. Brisas Del Norte Rio Danto', 'municipality_id' => '1'],
            ['name' => 'El Ocho', 'municipality_id' => '1'],
            ['name' => 'Tramo Milagro De Dios-Ponce', 'municipality_id' => '1'],
            ['name' => 'Lomas Del Curla', 'municipality_id' => '1'],
            ['name' => 'Sector Monte De Sion', 'municipality_id' => '1'],
            ['name' => 'Col. Monte De Sion', 'municipality_id' => '1'],
            ['name' => 'Tramo Sector No. 7', 'municipality_id' => '1'],
            ['name' => 'Tr. Club De Leones - 1ro. De Mayo', 'municipality_id' => '1'],
            ['name' => 'Villa Nueva', 'municipality_id' => '1'],
            ['name' => 'Col. Ramon Antonio Leva', 'municipality_id' => '1'],
            ['name' => 'Col. Juan Orlando', 'municipality_id' => '1'],
            ['name' => 'Col. 30 de Noviembre', 'municipality_id' => '1'],
            ['name' => 'Bo. Alvarado', 'municipality_id' => '1'],
            ['name' => 'Bo. El Centro', 'municipality_id' => '1'],
            ['name' => 'Bo. El Higuerito', 'municipality_id' => '1'],
            ['name' => 'Bo. El Iman', 'municipality_id' => '1'],
            ['name' => 'Bo. Independencia', 'municipality_id' => '1'],
            ['name' => 'Bo. Ingles', 'municipality_id' => '1'],
            ['name' => 'Bo. La Barra', 'municipality_id' => '1'],
            ['name' => 'Bo. La Gloria', 'municipality_id' => '1'],
            ['name' => 'Bo. La Isla', 'municipality_id' => '1'],
            ['name' => 'Bo. La Julia', 'municipality_id' => '1'],
            ['name' => 'Bo. Mazapan', 'municipality_id' => '1'],
            ['name' => 'Bo. Mejia', 'municipality_id' => '1'],
            ['name' => 'Bo. Potreritos', 'municipality_id' => '1'],
            ['name' => 'Bo. Solares Nuevos', 'municipality_id' => '1'],
            ['name' => 'Bo. Los Luchadores', 'municipality_id' => '1'],
            ['name' => 'Col. Brisas Del Cangrejal', 'municipality_id' => '1'],
            ['name' => 'Col. Miramar', 'municipality_id' => '1'],
            ['name' => 'Col. Los Maestros', 'municipality_id' => '1'],
            ['name' => 'Col. Naranjal', 'municipality_id' => '1'],
            ['name' => 'Col. Hondutel', 'municipality_id' => '1'],
            ['name' => 'Col. Alhambra', 'municipality_id' => '1'],
            ['name' => 'Col. La Merced', 'municipality_id' => '1'],
            ['name' => 'Col. Los Locutores', 'municipality_id' => '1'],
            ['name' => 'Col. Sitramacsa', 'municipality_id' => '1'],
            ['name' => 'Col. Zelaya', 'municipality_id' => '1'],
            ['name' => 'Col. Dantony', 'municipality_id' => '1'],
            ['name' => 'Col. Piñanza', 'municipality_id' => '1'],
            ['name' => 'Col. Portuaria', 'municipality_id' => '1'],
            ['name' => 'Col. R. Pineda', 'municipality_id' => '1'],
            ['name' => 'Col. Sarmiento', 'municipality_id' => '1'],
            ['name' => 'Col. Sitrafa O Blanquita', 'municipality_id' => '1'],
            ['name' => 'Col. Villa Real', 'municipality_id' => '1'],
            ['name' => 'Col. Los Angeles', 'municipality_id' => '1'],
            ['name' => 'Col. Sitramedys', 'municipality_id' => '1'],
            ['name' => 'Col. Los Cedros', 'municipality_id' => '1'],
            ['name' => 'Col. Bantral', 'municipality_id' => '1'],
            ['name' => 'Bo. Bella Vista', 'municipality_id' => '1'],
            ['name' => 'Bo. Buenos Aires', 'municipality_id' => '1'],
            ['name' => 'Bo. El Danto', 'municipality_id' => '1'],
            ['name' => 'Bo. San Jose', 'municipality_id' => '1'],
            ['name' => 'Col. Las Canelas', 'municipality_id' => '1'],
            ['name' => 'Col. Carmen Elena', 'municipality_id' => '1'],
            ['name' => 'Col. El Sauce', 'municipality_id' => '1'],
            ['name' => 'Col. El Herrero', 'municipality_id' => '1'],
            ['name' => 'Col. La Libertad', 'municipality_id' => '1'],
            ['name' => 'Col. Las Vegas', 'municipality_id' => '1'],
            ['name' => 'Col. Lempira', 'municipality_id' => '1'],
            ['name' => 'Col. Los Bomberos', 'municipality_id' => '1'],
            ['name' => 'Col. Melgar Castro #1', 'municipality_id' => '1'],
            ['name' => 'Col. Miraflores', 'municipality_id' => '1'],
            ['name' => 'Col. Noe Castillo', 'municipality_id' => '1'],
            ['name' => 'Col. San Juan', 'municipality_id' => '1'],
            ['name' => 'Col. San Judas Tadeo', 'municipality_id' => '1'],
            ['name' => 'Col. Satelite', 'municipality_id' => '1'],
            ['name' => 'Col. Suyapa', 'municipality_id' => '1'],
            ['name' => 'Col. Villa Linda', 'municipality_id' => '1'],
            ['name' => 'Col. Villa Los Pinos', 'municipality_id' => '1'],
            ['name' => 'Col. Villa ‘H’', 'municipality_id' => '1'],
            ['name' => 'Col. Atlante', 'municipality_id' => '1'],
            ['name' => 'Col. Azcona Del Hoyo', 'municipality_id' => '1'],
            ['name' => 'Col. El Toronjal I', 'municipality_id' => '1'],
            ['name' => 'Col. El Toronjal II', 'municipality_id' => '1'],
            ['name' => 'Col. Gonzalo Rivera', 'municipality_id' => '1'],
            ['name' => 'Col. Lomas De Buenos Aires', 'municipality_id' => '1'],
            ['name' => 'Col. Manzana 44', 'municipality_id' => '1'],
            ['name' => 'Col. Margie Dip', 'municipality_id' => '1'],
            ['name' => 'Col. Melgar Castro #2', 'municipality_id' => '1'],
            ['name' => 'Col. Municipal', 'municipality_id' => '1'],
            ['name' => 'Col. Murcia', 'municipality_id' => '1'],
            ['name' => 'Col. Las Mercedes', 'municipality_id' => '1'],
            ['name' => 'Col. Brisas De Buenos Aires', 'municipality_id' => '1'],
            ['name' => 'Col. Las Palmas (Danto)', 'municipality_id' => '1'],
            ['name' => 'Col. Gonzalo Rivera 2', 'municipality_id' => '1'],
            ['name' => 'Col. Altos De Miramar', 'municipality_id' => '1'],
            ['name' => 'Res. Las Colinas', 'municipality_id' => '1'],
            ['name' => 'Res. Villas Margarita', 'municipality_id' => '1'],
            ['name' => 'Res. Villa Cathleen', 'municipality_id' => '1'],
            ['name' => 'Col. Merrem', 'municipality_id' => '1'],
            ['name' => 'Bo. San Miguel', 'municipality_id' => '1'],
            ['name' => 'Col. Sierra Pina', 'municipality_id' => '1'],
            ['name' => 'Col. Casa Blanca No. 1', 'municipality_id' => '1'],
            ['name' => 'Col. El Roble', 'municipality_id' => '1'],
            ['name' => 'Col. Kawas O Florida', 'municipality_id' => '1'],
            ['name' => 'Col. Pizzati', 'municipality_id' => '1'],
            ['name' => 'Col. San Isidro', 'municipality_id' => '1'],
            ['name' => 'Col. Alameda', 'municipality_id' => '1'],
            ['name' => 'Col. Altiplano', 'municipality_id' => '1'],
            ['name' => 'Col. Boca Vieja', 'municipality_id' => '1'],
            ['name' => 'Col. El Roble No. 2', 'municipality_id' => '1'],
            ['name' => 'Col. Las Acacias', 'municipality_id' => '1'],
            ['name' => 'Col. El Manantial', 'municipality_id' => '1'],
            ['name' => 'Col. Prados De La Misericordia', 'municipality_id' => '1'],
            ['name' => 'Col. Proyecto Gringo', 'municipality_id' => '1'],
            ['name' => 'Col. Riviera', 'municipality_id' => '1'],
            ['name' => 'Col. Villa Mary', 'municipality_id' => '1'],
            ['name' => 'Col. Villa Del Este', 'municipality_id' => '1'],
            ['name' => 'Col. Villa Hermosa', 'municipality_id' => '1'],
            ['name' => 'Col. Modelo', 'municipality_id' => '1'],
            ['name' => 'Col. Los Bomberos No.2', 'municipality_id' => '1'],
            ['name' => 'Col. Nueva Esperanza', 'municipality_id' => '1'],
            ['name' => 'Res. Santander', 'municipality_id' => '1'],
            ['name' => 'Res. San Angel', 'municipality_id' => '1'],
            ['name' => 'Res. Maqueira', 'municipality_id' => '1'],
            ['name' => 'Res. Jardines Del Este', 'municipality_id' => '1'],
            ['name' => 'Res. El Prado', 'municipality_id' => '1'],
            ['name' => 'Res. Monte Hebron', 'municipality_id' => '1'],
            ['name' => 'Res. Villa Magnolia', 'municipality_id' => '1'],
            ['name' => 'Invasion Los Laureles', 'municipality_id' => '1'],
            ['name' => 'Muelle Cabotaje', 'municipality_id' => '1'],
            ['name' => 'Residencial Genova', 'municipality_id' => '1'],
            ['name' => 'Tr. Pizzati Pradera', 'municipality_id' => '1'],
            ['name' => 'Col. Las Palmas', 'municipality_id' => '1'],
            ['name' => 'Bo. Satuye', 'municipality_id' => '1'],
            ['name' => 'Col. Guadalupe', 'municipality_id' => '1'],
            ['name' => 'Col. La Pradera', 'municipality_id' => '1'],
            ['name' => 'Col. La Pradera No. 2', 'municipality_id' => '1'],
            ['name' => 'Res. Quinta Portales', 'municipality_id' => '1'],
            ['name' => 'Col. Villas Neem', 'municipality_id' => '1'],
            ['name' => 'Col. Bella Oriente', 'municipality_id' => '1'],
            ['name' => 'Col. Villas Neem II', 'municipality_id' => '1'],
            ['name' => 'Res. Monte Carlos', 'municipality_id' => '1'],
            ['name' => 'Col. Andalucia', 'municipality_id' => '1'],
            ['name' => 'Col. Andalucia 2', 'municipality_id' => '1'],
            ['name' => 'Col. La Gloria', 'municipality_id' => '1'],
            ['name' => 'Res. San Jorge', 'municipality_id' => '1'],
            ['name' => 'Res. Monte Real', 'municipality_id' => '1'],
            ['name' => 'Res. Puerto Escondido', 'municipality_id' => '1'],
            ['name' => 'Res. Villas Del Caribe', 'municipality_id' => '1'],
            ['name' => 'Res. Los Olivos', 'municipality_id' => '1'],
            ['name' => 'Res. Los Olivos II', 'municipality_id' => '1'],
            ['name' => 'Res. Monte Verde', 'municipality_id' => '1'],
            ['name' => 'Res. Residencial Del Bosque', 'municipality_id' => '1'],
            ['name' => 'Res. Santa Monica', 'municipality_id' => '1'],
            ['name' => 'Res. Montefresco', 'municipality_id' => '1'],
            ['name' => 'Res. El Triangulo', 'municipality_id' => '1'],
            ['name' => 'Quinta Los Laureles', 'municipality_id' => '1'],
            ['name' => 'Tramo Satuye - Boca Vieja', 'municipality_id' => '1'],
            ['name' => 'Jardines Del Satuye', 'municipality_id' => '1'],
            ['name' => 'Villas Vanessa Satuye', 'municipality_id' => '1'],
            ['name' => 'Sambo Creek', 'municipality_id' => '1'],
            ['name' => 'Res. Florida', 'municipality_id' => '1'],
            ['name' => 'Col. Valencia', 'municipality_id' => '1'],
            ['name' => 'Res. Monte Real del Bosque', 'municipality_id' => '1'],
            ['name' => 'Col. Las Tres Posas', 'municipality_id' => '1'],
        ];

        DB::table('localities')->insert($localities);
    }
}
