<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
         $medicines = [
            ['generic_name' => 'ACETAMINOFÉN (Sinónimo(s): Paracetamol)', 'presentation' => 'Frasco'],
            ['generic_name' => 'ACETAMINOFÉN (Sinónimo(s): Paracetamol)', 'presentation' => 'Frasco'],
            ['generic_name' => 'ACETAMINOFÉN (Sinónimo(s): Paracetamol)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ACETAMINOFÉN (Sinónimo(s): Paracetamol)', 'presentation' => 'Vial'],
            ['generic_name' => 'ACETAZOLAMIDA', 'presentation' => 'Tableta'],
            ['generic_name' => 'ACETILCISTEÍNA', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ACETILCISTEÍNA', 'presentation' => 'Sobre'],
            ['generic_name' => 'ACICLOVIR', 'presentation' => 'Frasco'],
            ['generic_name' => 'ACICLOVIR', 'presentation' => 'Tableta'],
            ['generic_name' => 'ACICLOVIR (sal sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'ÁCIDO ACETIL SALICÍLICO', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO FÓLICO', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO FÓLICO', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO TRANEXÁMICO', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ÁCIDO TRICLOROACÉTICO', 'presentation' => 'Frasco'],
            ['generic_name' => 'ÁCIDO VALPROICO (sódico)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO VALPROICO (valproato sódico)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'ÁCIDO VALPROICO (valproato sódico)', 'presentation' => 'Frasco'],
            ['generic_name' => 'ADENOSINA', 'presentation' => 'Vial'],
            ['generic_name' => 'ADRENALINA (clorhidrato) (Sinónimo(s): Epinefrina)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AGUA ESTÉRIL PARA INYECCIÓN', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AGUA ESTÉRIL PARA INYECCIÓN', 'presentation' => 'Bolsa'],
            ['generic_name' => 'ALBENDAZOL', 'presentation' => 'Frasco'],
            ['generic_name' => 'ALBÚMINA HUMANA', 'presentation' => 'Vial'],
            ['generic_name' => 'ALFACALCIDOL (Vitamina D3)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALFACALCIDOL (Vitamina D3)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALFAMETILDOPA (Sinónimo(s): Metildopa)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALFUZOSINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALOPURINOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALOPURINOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMIKACINA (sulfato)', 'presentation' => 'Vial'],
            ['generic_name' => 'AMIKACINA (sulfato)', 'presentation' => 'Vial'],
            ['generic_name' => 'AMINOFILINA', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AMIODARONA (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AMIODARONA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMITRIPTILINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMLODIPINO (besilato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMOXICILINA (trihidrato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'AMOXICILINA (trihidrato)', 'presentation' => 'Cápsula'],
            ['generic_name' => 'AMOXICILINA (trihidrato) + ÁCIDO CLAVULÁNICO (clavulanato de potasio)', 'presentation' => 'Frasco'],
            ['generic_name' => 'AMOXICILINA (trihidrato) + ÁCIDO CLAVULÁNICO (clavulanato de potasio)', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMPICILINA (anhidra o sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'AMPICILINA + SULBACTAM', 'presentation' => 'Vial'],
            ['generic_name' => 'ATORVASTATINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'ATORVASTATINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'ATRACURIO (besilato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ATROPINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'ATROPINA (sulfato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AZELASTINA (clorhidrato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'AZITROMICINA', 'presentation' => 'Vial'],
            ['generic_name' => 'AZITROMICINA (anhidra o dihidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'AZITROMICINA (dihidrato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'BECLOMETASONA (dipropionato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'BECLOMETASONA (dipropionato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'BECLOMETASONA (dipropionato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'BETAMETASONA (valerato)', 'presentation' => 'Tubo'],
            ['generic_name' => 'BETAMETASONA (valerato) ó DEXAMETASONA + DOBESILATO DE CALCIO + LIDOCAÍNA', 'presentation' => 'Tubo'],
            ['generic_name' => 'BIPERIDENO (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'BIPERIDENO (lactato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'BISOPROLOL (fumarato o hemifumarato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'BISOPROLOL (fumarato o hemifumarato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'BUPIVACAÍNA + GLUCOSA (sin preservantes derivados del parabeno)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'BUPIVACAÍNA (sin preservantes derivados del parabeno)', 'presentation' => 'Vial'],
            ['generic_name' => 'CAFEÍNA (citrato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CAFEÍNA (citrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'CALAMINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'CALCIO (carbonato) (equivalente a calcio elemental)', 'presentation' => 'Tableta'],
            ['generic_name' => 'CALCIO (carbonato) (equivalente a calcio elemental) + VITAMINA D', 'presentation' => 'Tableta'],
            ['generic_name' => 'CALCIO (gluconato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'CALCIPOTRIOL (monohidrato) + BETAMETASONA (dipropionato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CALCIPOTRIOL (monohidrato) + BETAMETASONA (dipropionato)', 'presentation' => 'Tubo'],
            ['generic_name' => 'CARBAMAZEPINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'CARBÓN VEGETAL ACTIVADO', 'presentation' => 'Frasco'],
            ['generic_name' => 'CEFALEXINA (monohidrato)', 'presentation' => 'Cápsula'],
            ['generic_name' => 'CEFAZOLINA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFIXIMA (trihidrato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CEFOTAXIMA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFOXITINA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFTAZIDIMA (pentahidratado)', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFTRIAXONA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFTRIAXONA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'CICLOSPORINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'CIPROFLOXACINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'CIPROFLOXACINA (lactato)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'CLARITROMICINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'CLARITROMICINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'CLINDAMICINA (clorhidrato de palmitato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CLINDAMICINA (clorhidrato)', 'presentation' => 'Cápsula'],
            ['generic_name' => 'CLINDAMICINA (fosfato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'CLOBETASOL', 'presentation' => 'Tubo'],
            ['generic_name' => 'CLONAZEPAM', 'presentation' => 'Tableta'],
            ['generic_name' => 'CLOPIDOGREL (bisulfato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'CLORANFENICOL', 'presentation' => 'Frasco'],
            ['generic_name' => 'CLORHEXIDINA (gluconato)', 'presentation' => 'Galón'],
            ['generic_name' => 'CLORHEXIDINA (gluconato) + CETRIMIDA', 'presentation' => 'Galón'],
            ['generic_name' => 'CLOTRIMAZOL', 'presentation' => 'Óvulo'],
            ['generic_name' => 'COLCHICINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'DAPSONA', 'presentation' => 'Tableta'],
            ['generic_name' => 'DEXAMETASONA (fosfato)', 'presentation' => 'Vial'],
            ['generic_name' => 'DEXKETOPROFENO (trometanol)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'DIAZEPAM', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DICLOFENACO (sódico)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DICLOXACILINA (sódica)', 'presentation' => 'Frasco'],
            ['generic_name' => 'DICLOXACILINA (sódica)', 'presentation' => 'Cápsula'],
            ['generic_name' => 'DIFENHIDRAMINA (clorhidrato)', 'presentation' => 'Vial'],
            ['generic_name' => 'DIFENHIDRAMINA (clorhidrato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'DIFENHIDRAMINA (clorhidrato)', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'DIGOXINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'DIGOXINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'DIGOXINA', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DIMENHIDRINATO', 'presentation' => 'Supositorio'],
            ['generic_name' => 'DIMENHIDRINATO', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'DOBESILATO DE CALCIO', 'presentation' => 'Cápsula'],
            ['generic_name' => 'DOBUTAMINA (clorhidrato)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'DOPAMINA (clorhidrato)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'DOXICICLINA (clorhidrato o hiclato)', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'EFEDRINA (sulfato)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'ENALAPRIL (maleato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ENALAPRIL (maleato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ENALAPRIL (maleato) (Sinónimo(s): Enalaprilato)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'ENOXAPARINA (sódica)', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'ENOXAPARINA (sódica)', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'ERGONOVINA (maleato) (Sinónimo(s): Ergometrina, Metilergonovina, Metilergometrina, Metilergobasina)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ERITROMICINA (estearato o etilsuccinato) (no estolato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ERITROMICINA (etilsuccinato) (no estolato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'ERITROPOYETINA α (alfa recombinante humana) (Sinónimo(s): Epoetina Alfa)', 'presentation' => 'Vial o Jeringa'],
            ['generic_name' => 'ERITROPOYETINA β (beta recombinante humana) (Sinónimo(s): Epoetina Beta)', 'presentation' => 'Vial o Jeringa'],
            ['generic_name' => 'ESOMEPRAZOL', 'presentation' => 'Sobre'],
            ['generic_name' => 'ESPIRONOLACTONA', 'presentation' => 'Tableta'],
            ['generic_name' => 'ESTREPTOQUINASA', 'presentation' => 'Vial'],
            ['generic_name' => 'ESTRÓGENOS CONJUGADOS', 'presentation' => 'Tableta'],
            ['generic_name' => 'FACTOR DE COAGULACIÓN VIII', 'presentation' => 'Vial'],
            ['generic_name' => 'FENITOÍNA (sódica) (Sinónimo(s): Difenilhidantoína)', 'presentation' => 'Frasco'],
            ['generic_name' => 'FENITOÍNA (sódica) (Sinónimo(s): Difenilhidantoína)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'FENITOÍNA (sódica) (Sinónimo(s): Difenilhidantoína)', 'presentation' => 'Cápsula'],
            ['generic_name' => 'FENOBARBITAL', 'presentation' => 'Tableta'],
            ['generic_name' => 'FENOBARBITAL (sódico)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'FENTANILO (citrato)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'FLUCONAZOL', 'presentation' => 'Vial'],
            ['generic_name' => 'FLUCONAZOL', 'presentation' => 'Frasco'],
            ['generic_name' => 'FLUCONAZOL', 'presentation' => 'Cápsula'],
            ['generic_name' => 'FLUMAZENIL', 'presentation' => 'Ampolla'],
            ['generic_name' => 'FLUOROMETOLONA', 'presentation' => 'Frasco'],
            ['generic_name' => 'FOSFATO (sódico monobásico) + FOSFATO (sódico dibásico)', 'presentation' => 'Frasco'],
            ['generic_name' => 'FOSFATO (sódico monobásico) + FOSFATO (sódico dibásico)', 'presentation' => 'Frasco'],
            ['generic_name' => 'FUROSEMIDA', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'FUROSEMIDA', 'presentation' => 'Tableta'],
            ['generic_name' => 'GENTAMICINA (sulfato)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'GENTAMICINA (sulfato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'GLICLAZIDA', 'presentation' => 'Tableta'],
            ['generic_name' => 'GLUTARALDEHÍDO', 'presentation' => 'Galón'],
            ['generic_name' => 'HALOPERIDOL', 'presentation' => 'Ampolla'],
            ['generic_name' => 'HEPARINA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'HIDRALAZINA (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'HIDRALAZINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'HIDROCLOROTIAZIDA', 'presentation' => 'Tableta'],
            ['generic_name' => 'HIDROCORTISONA (acetato)', 'presentation' => 'Tubo'],
            ['generic_name' => 'HIDROCORTISONA (succinato sódico)', 'presentation' => 'Vial'],
            ['generic_name' => 'HIDROCORTISONA (succinato sódico)', 'presentation' => 'Vial'],
            ['generic_name' => 'HIDRÓXIDO DE ALUMINIO + HIDRÓXIDO DE MAGNESIO', 'presentation' => 'Frasco'],
            ['generic_name' => 'HIERRO (sacarosa) (complejo de sacarosa e hidróxido de hierro)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'HIERRO (sulfato)', 'presentation' => 'Tableta/Gragea'],
            ['generic_name' => 'HIERRO (sulfato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'HIOSCINA (butilbromuro) (Sinónimo(s): Escopolamina, Butilescopolamina)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'HIOSCINA (butilbromuro) (Sinónimo(s): Escopolamina, Butilescopolamina)', 'presentation' => 'Tableta'],
            ['generic_name' => 'IBUPROFENO', 'presentation' => 'Frasco'],
            ['generic_name' => 'IBUPROFENO', 'presentation' => 'Tableta'],
            ['generic_name' => 'IMIPENEM (monohidrato) + CILASTATINA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'IMIPRAMINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'INMUNOGLOBULINA ANTI "D" (RH+)', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA ANTIHEPATITIS "B"', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA ANTIRRÁBICA', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA ANTITETÁNICA', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA HUMANA NORMAL', 'presentation' => 'Vial'],
            ['generic_name' => 'INSULINA CRISTALINA', 'presentation' => 'Vial'],
            ['generic_name' => 'INSULINA ISOFÁNICA HUMANA NPH', 'presentation' => 'Vial'],
            ['generic_name' => 'IPRATROPIO (bromuro)', 'presentation' => 'Frasco'],
            ['generic_name' => 'IPRATROPIO (bromuro)', 'presentation' => 'Frasco'],
            ['generic_name' => 'IRBESARTÁN', 'presentation' => 'Tableta'],
            ['generic_name' => 'ISOSORBIDE (dinitrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ISOSORBIDE (mononitrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'KETAMINA (clorhidrato)', 'presentation' => 'Vial'],
            ['generic_name' => 'KETOCONAZOL', 'presentation' => 'Tubo'],
            ['generic_name' => 'LACTATO DE SODIO + ELECTROLITOS MIXTOS (Solución Hartmann o Ringer Lactato)', 'presentation' => 'Frasco/Bolsa'],
            ['generic_name' => 'LACTULOSA', 'presentation' => 'Frasco'],
            ['generic_name' => 'LATANOPROST', 'presentation' => 'Frasco'],
            ['generic_name' => 'LEVODOPA + CARBIDOPA', 'presentation' => 'Tableta'],
            ['generic_name' => 'LEVOFLOXACINA (hemihidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'LEVOFLOXACINA (hemihidrato)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'LEVOTIROXINA (sódica)', 'presentation' => 'Tableta'],
            ['generic_name' => 'LIDOCAÍNA', 'presentation' => 'Frasco'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) + EPINEFRINA', 'presentation' => 'Vial en cartucho'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) + EPINEFRINA (sin preservantes derivados del parabeno)', 'presentation' => 'Vial'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) (con preservantes)', 'presentation' => 'Vial'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) (sin preservantes derivados del parabeno)', 'presentation' => 'Vial'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) (sin vasoconstrictor)', 'presentation' => 'Vial en cartucho'],
            ['generic_name' => 'LORATADINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'LORATADINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'LORAZEPAM', 'presentation' => 'Tableta'],
            ['generic_name' => 'LUBRICANTE ESTÉRIL', 'presentation' => 'Tubo'],
            ['generic_name' => 'MAGNESIO (sulfato heptahidratado)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MANITOL', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'MEPERIDINA (clorhidrato) (Sinónimo(s): Petidina (clorhidrato))', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MEROPENEM', 'presentation' => 'Vial'],
            ['generic_name' => 'METFORMINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'METILCELULOSA (Sinónimo(s): Hidroxipropil Metilcelulosa, Hipromelosa, Carboximetilcelulosa, Carmelosa)', 'presentation' => 'Frasco'],
            ['generic_name' => 'METILPREDNISOLONA (acetato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'METILPREDNISOLONA (succinato sódico)', 'presentation' => 'Vial'],
            ['generic_name' => 'METILPREDNISOLONA (succinato sódico)', 'presentation' => 'Vial'],
            ['generic_name' => 'METOCARBAMOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'METOCLOPRAMIDA (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'METOCLOPRAMIDA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'METRONIDAZOL', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'METRONIDAZOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'METRONIDAZOL', 'presentation' => 'Tubo'],
            ['generic_name' => 'METRONIDAZOL (benzoato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'MICONAZOL', 'presentation' => 'Tubo'],
            ['generic_name' => 'MIDAZOLAM (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MISOPROSTOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'MORFINA (clorhidrato o sulfato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MOXIFLOXACINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'MULTIVITAMINAS ADULTOS', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'MULTIVITAMINAS PEDIÁTRICAS', 'presentation' => 'Frasco'],
            ['generic_name' => 'MULTIVITAMINAS PRENATALES', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'NAFAZOLINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'NALOXONA (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'NATAMICINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'NEOSTIGMINA (metilsulfato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'NIFEDIPINA', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'NIFEDIPINA (liberación inmediata)', 'presentation' => 'Cápsula'],
            ['generic_name' => 'NISTATINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'NITROFURANTOÍNA', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'NITROGLICERINA (Sinónimo(s): Trinitrato de Glicerilo)', 'presentation' => 'Vial'],
            ['generic_name' => 'NITROPRUSIATO DE SODIO', 'presentation' => 'Vial/Ampolla'],
            ['generic_name' => 'NORADRENALINA (Sinónimo(s): Norepinefrina, Levarterenol)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'OCTREÓTIDA (acetato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'OMEPRAZOL', 'presentation' => 'Cápsula'],
            ['generic_name' => 'OMEPRAZOL', 'presentation' => 'Vial'],
            ['generic_name' => 'OXACILINA (sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'OXIBUTININA', 'presentation' => 'Tableta'],
            ['generic_name' => 'OXITETRACICLINA (clorhidrato) + POLIMIXINA B (sulfato)', 'presentation' => 'Tubo'],
            ['generic_name' => 'OXITOCINA', 'presentation' => 'Ampolla'],
            ['generic_name' => 'PENICILINA G BENZATÍNICA (Sinónimo(s): Bencilpenicilina benzatina)', 'presentation' => 'Vial'],
            ['generic_name' => 'PENICILINA G CRISTALINA (Sinónimo(s): Bencilpenicilina o Penicilina G Sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'PENICILINA G CRISTALINA (Sinónimo(s): Bencilpenicilina o Penicilina G Sódica)', 'presentation' => 'Vial'],
            ['generic_name' => 'PENICILINA G PROCAÍNICA (Sinónimo(s): Bencilpenicilina procaína)', 'presentation' => 'Vial'],
            ['generic_name' => 'PERMETRINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'PERMETRINA', 'presentation' => 'Tubo'],
            ['generic_name' => 'PETROLATO SÓLIDO', 'presentation' => 'Tarro/Frasco'],
            ['generic_name' => 'PIPERACILINA (sódica) + TAZOBACTAM (sódico)', 'presentation' => 'Vial'],
            ['generic_name' => 'PIRIDOXINA (clorhidrato) (Sinónimo(s): Vitamina B6)', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'PIRIMETAMINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'POLIESTIRENO SULFONATO', 'presentation' => 'Sobre'],
            ['generic_name' => 'POLIMIXINA B + NEOMICINA + BACITRACINA', 'presentation' => 'Tubo'],
            ['generic_name' => 'POTASIO (cloruro)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'PREDNISOLONA (fosfato sódico)', 'presentation' => 'Frasco'],
            ['generic_name' => 'PREDNISONA', 'presentation' => 'Tableta'],
            ['generic_name' => 'PREDNISONA', 'presentation' => 'Tableta'],
            ['generic_name' => 'PROPILTIOURACILO', 'presentation' => 'Tableta'],
            ['generic_name' => 'PROPOFOL (con o sin E.D.T.A.)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'PROPRANOLOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'PROTAMINA (sulfato o clorhidrato)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'RANITIDINA (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'Saccharomyces boulardii', 'presentation' => 'Sobre'],
            ['generic_name' => 'SALBUTAMOL (sulfato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'SALBUTAMOL (sulfato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'SALES DE REHIDRATACIÓN ORAL', 'presentation' => 'Sobre'],
            ['generic_name' => 'SALICILATO DE METILO', 'presentation' => 'Tarro'],
            ['generic_name' => 'SELEGILINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'SEVOFLURANO', 'presentation' => 'Vial'],
            ['generic_name' => 'SODIO (bicarbonato)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'SODIO (cloruro)', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro)', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro)', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro)', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro)', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SUCCINILCOLINA (cloruro) (Sinónimo(s): Suxametonio (cloruro))', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'SUERO ANTIOFÍDICO (polivalente anticoral)', 'presentation' => 'Vial'],
            ['generic_name' => 'SUERO ANTIOFÍDICO (polivalente anticrotálido)', 'presentation' => 'Vial'],
            ['generic_name' => 'SULFADIAZINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'SULFADIAZINA DE PLATA', 'presentation' => 'Tubo'],
            ['generic_name' => 'SURFACTANTE EXÓGENO PULMONAR NATURAL', 'presentation' => 'Vial'],
            ['generic_name' => 'TETRACAÍNA', 'presentation' => 'Frasco'],
            ['generic_name' => 'TIAMINA (clorhidrato) (Sínónimo(s): Vitamina B1)', 'presentation' => 'Vial'],
            ['generic_name' => 'TIAMINA (clorhidrato) (Sínónimo(s): Vitamina B1)', 'presentation' => 'Tableta'],
            ['generic_name' => 'TIMOLOL (maleato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'TIMOLOL (maleato) + DORZOLAMIDA (hidrocloruro)', 'presentation' => 'Frasco'],
            ['generic_name' => 'TINIDAZOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'TIOPENTAL (sódico)', 'presentation' => 'Vial'],
            ['generic_name' => 'TOBRAMICINA', 'presentation' => 'Frasco'],
            ['generic_name' => 'TRAMADOL (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'TRIMETOPRIM + SULFAMETOXAZOL', 'presentation' => 'Frasco'],
            ['generic_name' => 'TRIMETOPRIM + SULFAMETOXAZOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'TROPICAMIDA', 'presentation' => 'Frasco'],
            ['generic_name' => 'VANCOMICINA (clorhidrato)', 'presentation' => 'Vial'],
            ['generic_name' => 'VERAPAMILO (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'VITAMINA K1 (Sinónimo(s): Fitomenadiona)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'WARFARINA (sódica)', 'presentation' => 'Tableta'],
            ['generic_name' => 'YODO + POLIVINIL PIRROLIDONA (yodo povidone)', 'presentation' => 'Galón/Envase'],
            ['generic_name' => 'ZINC (sulfato)', 'presentation' => 'Frasco'],
            ['generic_name' => 'PODOFILINA (Podofilotoxina)', 'presentation' => 'Frasco'],
            ['generic_name' => 'SUERO FABOTERÁPICO (polivalente antiarácnido)', 'presentation' => 'Vial'],
            ['generic_name' => 'ALBENDAZOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'ABIRATERONA (acetato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'APREPITANT', 'presentation' => 'Set'],
            ['generic_name' => 'ASPARAGINASA (Sinónimo(s): L-Asparaginase)', 'presentation' => 'Vial'],
            ['generic_name' => 'AZATIOPRINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'BEVACIZUMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'BEVACIZUMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'BICALUTAMIDA', 'presentation' => 'Tableta'],
            ['generic_name' => 'BLEOMICINA (sulfato)', 'presentation' => 'Vial'],
            ['generic_name' => 'BORTEZOMIB', 'presentation' => 'Vial'],
            ['generic_name' => 'CAPECITABINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'CARBOPLATINO', 'presentation' => 'Vial'],
            ['generic_name' => 'CETUXIMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'CICLOFOSFAMIDA', 'presentation' => 'Tableta'],
            ['generic_name' => 'CICLOFOSFAMIDA', 'presentation' => 'Vial'],
            ['generic_name' => 'CICLOFOSFAMIDA', 'presentation' => 'Vial'],
            ['generic_name' => 'CISPLATINO', 'presentation' => 'Vial'],
            ['generic_name' => 'CITARABINA', 'presentation' => 'Vial'],
            ['generic_name' => 'CITARABINA', 'presentation' => 'Vial'],
            ['generic_name' => 'CLORAMBUCILO (cloruro)', 'presentation' => 'Tableta'],
            ['generic_name' => 'DACARBAZINA', 'presentation' => 'Vial'],
            ['generic_name' => 'DACTINOMICINA (Sinónimo(s): Actinomicina-D)', 'presentation' => 'Vial'],
            ['generic_name' => 'DOCETAXEL', 'presentation' => 'Vial'],
            ['generic_name' => 'DOCETAXEL', 'presentation' => 'Vial'],
            ['generic_name' => 'DOXORUBICINA (clorhidrato)', 'presentation' => 'Vial'],
            ['generic_name' => 'DOXORUBICINA (clorhidrato)', 'presentation' => 'Vial'],
            ['generic_name' => 'ERLOTINIB (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'ETOPÓSIDO (Sinónimo(s): VP-16)', 'presentation' => 'Vial'],
            ['generic_name' => 'EXEMESTANO', 'presentation' => 'Gragea'],
            ['generic_name' => 'FACTOR DE COAGULACIÓN IX', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'FACTOR DE COAGULACIÓN VIIa RECOMBINANTE (Sinónimo(s): Eptacog alfa (activado), rFVIIa)', 'presentation' => 'Vial'],
            ['generic_name' => 'FILGRASTIM (factor estimulador de colonias de granulocitos)', 'presentation' => 'Vial o Jeringa'],
            ['generic_name' => 'FLUDARABINA (fosfato)', 'presentation' => 'Vial'],
            ['generic_name' => 'FLUOROURACILO (Sinónimo(s): 5-FU, 5-Fluorouracilo)', 'presentation' => 'Vial'],
            ['generic_name' => 'FOLINATO DE CALCIO (Sinónimo(s): Leucovorina cálcica, ácido folínico)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'GEMCITABINA', 'presentation' => 'Vial'],
            ['generic_name' => 'GEMCITABINA', 'presentation' => 'Vial'],
            ['generic_name' => 'GOSERELINA (acetato)', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'HIDROXIUREA (Sinónimo(s): Hidroxicarbamida)', 'presentation' => 'Cápsula'],
            ['generic_name' => 'IFOSFAMIDA', 'presentation' => 'Vial'],
            ['generic_name' => 'INTERFERÓN BETA 1A', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'IRINOTECANO (clorhidrato)', 'presentation' => 'Vial'],
            ['generic_name' => 'LEFLUNOMIDA', 'presentation' => 'Tableta'],
            ['generic_name' => 'MELFALAN', 'presentation' => 'Tableta'],
            ['generic_name' => 'MERCAPTOPURINA (Sinónimo(s): 6-MP, 6-Mercaptopurina)', 'presentation' => 'Tableta'],
            ['generic_name' => 'MESNA (Sinónimo(s): 2-mercaptoetanol sulfonato de sodio)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'METOTREXATO', 'presentation' => 'Tableta'],
            ['generic_name' => 'METOTREXATO', 'presentation' => 'Vial'],
            ['generic_name' => 'METOTREXATO', 'presentation' => 'Vial'],
            ['generic_name' => 'ONDANSETRON (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'OXALIPLATINO', 'presentation' => 'Vial'],
            ['generic_name' => 'OXALIPLATINO', 'presentation' => 'Vial'],
            ['generic_name' => 'OXICODONA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'PACLITAXEL', 'presentation' => 'Vial'],
            ['generic_name' => 'PACLITAXEL', 'presentation' => 'Vial'],
            ['generic_name' => 'RITUXIMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'RITUXIMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'SOMATROPINA', 'presentation' => 'Vial o dispositivo precargado'],
            ['generic_name' => 'TAMOXIFENO (citrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'TEMOZOLAMIDA', 'presentation' => 'Cápsula'],
            ['generic_name' => 'TEMOZOLAMIDA', 'presentation' => 'Cápsula'],
            ['generic_name' => 'TOCILIZUMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'TOCILIZUMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'TRASTUZUMAB', 'presentation' => 'Vial'],
            ['generic_name' => 'VINBLASTINA (sulfato)', 'presentation' => 'Vial'],
            ['generic_name' => 'VINCRISTINA (sulfato)', 'presentation' => 'Vial'],
            ['generic_name' => 'VINORELBINA (bitartrato)', 'presentation' => 'Vial'],
            ['generic_name' => 'MORFINA (clorhidrato o sulfato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'MIDAZOLAM (clorhidrato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'RISPERIDONA', 'presentation' => 'Tableta'],
            ['generic_name' => 'LITIO (carbonato)', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'CLOZAPINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'FLUOXETINA (clorhidrato)', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'FLUFENAZINA (decanoato o enantato)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'SERTRALINA (clorhidrato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'QUETIAPINA (fumarato)', 'presentation' => 'Tableta'],
            ['generic_name' => 'BUDESONIDA + FORMOTEROL', 'presentation' => 'Frasco'],
            ['generic_name' => 'CABERGOLINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'HALOPERIDOL', 'presentation' => 'Tableta'],
            ['generic_name' => 'APIXABAN', 'presentation' => 'Tableta'],
            ['generic_name' => 'BUDESONIDA (Micronizada)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'BUDESONIDA + FORMOTEROL', 'presentation' => 'Frasco'],
            ['generic_name' => 'FUROSEMIDA', 'presentation' => 'Frasco'],
            ['generic_name' => 'LEVETIRACETAM', 'presentation' => 'Tableta'],
            ['generic_name' => 'LEVETIRACETAM', 'presentation' => 'Frasco'],
            ['generic_name' => 'LEVOTIROXINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'METIMAZOL (TIAMAZOL)', 'presentation' => 'Tableta'],
            ['generic_name' => 'SODIO (cloruro) (Solución Hipertónica)', 'presentation' => 'Bolsa'],
            ['generic_name' => 'GADOBUTROL', 'presentation' => 'Vial'],
            ['generic_name' => 'IOPRAMIDA', 'presentation' => 'Vial'],
            ['generic_name' => 'CLADRIBINA', 'presentation' => 'Tableta'],
            ['generic_name' => 'VANCOMICINA', 'presentation' => 'Cápsula'],
            ['generic_name' => 'PRAZIQUANTEL', 'presentation' => 'Tableta'],
        ];

        foreach ($medicines as $medicine) {
            Medicine::create($medicine);
        }
    }
}