<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medicines = [
            ['generic_name' => 'ACETAMINOFÉN Sinónimo(s): Paracetamol 100 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'ACETAMINOFÉN Sinónimo(s): Paracetamol 120 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'ACETAMINOFÉN Sinónimo(s): Paracetamol 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ACETAMINOFÉN Sinónimo(s): Paracetamol 10 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'ACETAZOLAMIDA 250 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ACETILCISTEÍNA 100 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ACETILCISTEÍNA 600 mg', 'presentation' => 'Sobre'],
            ['generic_name' => 'ACICLOVIR 200 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'ACICLOVIR 400 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ACICLOVIR (sal sódica) 250 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'ÁCIDO ACETIL SALICÍLICO 100 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO FÓLICO 1 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO FÓLICO 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO TRANEXÁMICO 100 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ÁCIDO TRICLOROACÉTICO 80 al 90%', 'presentation' => 'Frasco'],
            ['generic_name' => 'ÁCIDO VALPROICO (sódico) 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ÁCIDO VALPROICO (valproato sódico) 100 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'ÁCIDO VALPROICO (valproato sódico) 200 - 250 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'ADENOSINA 3 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'ADRENALINA (clorhidrato) Sinónimo(s): Epinefrina 1 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AGUA ESTÉRIL PARA INYECCIÓN Agua esteril para inyección en envase de 10 ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AGUA ESTÉRIL PARA INYECCIÓN Agua estéril para inyección en envase de 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'ALBENDAZOL 400 mg', 'presentation' => 'Frasco'],
            ['generic_name' => 'ALBÚMINA HUMANA 20 - 25% (Eq 200 - 250 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'ALFACALCIDOL (Vitamina D3) 0.25 mcg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALFACALCIDOL (Vitamina D3) 1 mcg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALFAMETILDOPA Sinónimo(s): Metildopa 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALFUZOSINA (clorhidrato) 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALOPURINOL 100 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ALOPURINOL 300 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMIKACINA (sulfato) 50 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'AMIKACINA (sulfato) 250 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'AMINOFILINA 250 mg (25 mg / ml)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AMIODARONA (clorhidrato) 50 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AMIODARONA (clorhidrato) 200 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMITRIPTILINA (clorhidrato) 25 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMLODIPINO (besilato) 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMOXICILINA (trihidrato) 250 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'AMOXICILINA (trihidrato) 500 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'AMOXICILINA (trihidrato) + ÁCIDO CLAVULÁNICO (clavulanato de potasio) (250 mg + 62.5 mg) / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'AMOXICILINA (trihidrato) + ÁCIDO CLAVULÁNICO (clavulanato de potasio) 875 mg + 125 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'AMPICILINA (anhidra o sódica) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'AMPICILINA + SULBACTAM 1 g + 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'ATORVASTATINA 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ATORVASTATINA 40 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ATRACURIO (besilato) 10 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ATROPINA 1% (Eq 10 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'ATROPINA (sulfato) 1 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'AZELASTINA (clorhidrato) 0.05% (Eq 0.5 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'AZITROMICINA 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'AZITROMICINA (anhidra o dihidrato) 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'AZITROMICINA (dihidrato) 200 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'BECLOMETASONA (dipropionato) 50 mcg / aplicación', 'presentation' => 'Frasco'],
            ['generic_name' => 'BECLOMETASONA (dipropionato) 250 mcg / aplicación', 'presentation' => 'Frasco'],
            ['generic_name' => 'BETAMETASONA (valerato) 0.1% (Eq 1 mg / g)', 'presentation' => 'Tubo'],
            ['generic_name' => 'BETAMETASONA (valerato) ó DEXAMETASONA + DOBESILATO DE CALCIO + LIDOCAÍNA 0.025 g + 4 g + 2 g', 'presentation' => 'Tubo'],
            ['generic_name' => 'BIPERIDENO (clorhidrato) 2 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'BIPERIDENO (lactato) 5 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'BISOPROLOL (fumarato o hemifumarato) 2.5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'BISOPROLOL (fumarato o hemifumarato) 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'BUPIVACAÍNA + GLUCOSA (sin preservantes derivados del parabeno) 0.5% (Eq 5 mg / ml) + 7.5 - 8% (Eq 75 - 80 mg / ml)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'BUPIVACAÍNA (sin preservantes derivados del parabeno) 0.5% (Eq 5 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'CAFEÍNA (citrato) 20 mg / ml (Eq 10 mg / ml de cafeína base)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CAFEÍNA (citrato) 20 mg / ml (Eq 10 mg / ml de cafeína base)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'CALAMINA 8% (Eq 8 g / 100 ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CALCIO (carbonato) (equivalente a calcio elemental) 600 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CALCIO (carbonato) (equivalente a calcio elemental) + VITAMINA D 600 mg + 200 UI', 'presentation' => 'Tableta'],
            ['generic_name' => 'CALCIO (gluconato) 10% (Eq 100 mg / ml)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'CALCIPOTRIOL (monohidrato) + BETAMETASONA (dipropionato) 50 mcg + 0.5 mg', 'presentation' => 'Frasco'],
            ['generic_name' => 'CALCIPOTRIOL (monohidrato) + BETAMETASONA (dipropionato) 50 mcg + 0.5 mg', 'presentation' => 'Tubo'],
            ['generic_name' => 'CARBAMAZEPINA 200 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CARBÓN VEGETAL ACTIVADO 50 g', 'presentation' => 'Frasco'],
            ['generic_name' => 'CEFALEXINA (monohidrato) 500 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'CEFAZOLINA (sódica) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFIXIMA (trihidrato) 100 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'CEFOTAXIMA (sódica) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFOXITINA (sódica) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFTAZIDIMA (pentahidratado) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFTRIAXONA (sódica) 250 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CEFTRIAXONA (sódica) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'CICLOSPORINA 0.1% (Eq 1 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CIPROFLOXACINA (clorhidrato) 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CIPROFLOXACINA (lactato) 200 mg (2 mg / ml)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'CLARITROMICINA 250 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'CLARITROMICINA 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CLINDAMICINA (clorhidrato de palmitato) 75 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'CLINDAMICINA (clorhidrato) 300 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'CLINDAMICINA (fosfato) 150 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'CLOBETASOL 0.0005', 'presentation' => 'Tubo'],
            ['generic_name' => 'CLONAZEPAM 2 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CLOPIDOGREL (bisulfato) 75 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CLORANFENICOL 0.5% (Eq 5 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'CLORHEXIDINA (gluconato) 20% V/V (Eq 4% P/V)', 'presentation' => 'Galón'],
            ['generic_name' => 'CLORHEXIDINA (gluconato) + CETRIMIDA 1.5% + 15%', 'presentation' => 'Galón'],
            ['generic_name' => 'CLOTRIMAZOL 500 mg', 'presentation' => 'Óvulo'],
            ['generic_name' => 'COLCHICINA 0.5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'DAPSONA 100 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'DEXAMETASONA (fosfato) 4 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'DEXKETOPROFENO (trometanol) 25 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO 5% + 0.3% en envase conteniendo 250 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO 5% + 0.3% en envase conteniendo 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO 5% + 0.45% en envase conteniendo 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO 5% + 0.45% en envase conteniendo 1000 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO 5% + 0.9% en envase conteniendo 250 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA + CLORURO DE SODIO 5% + 0.9% en envase conteniendo 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA 10% en envase conteniendo 250 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA 10% en envase conteniendo 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA 5% en envase conteniendo 1000 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA 5% en envase conteniendo 250 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA 5% en envase conteniendo 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'DEXTROSA EN AGUA 50% en envase conteniendo 50 ml', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'DIAZEPAM 5 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DICLOFENACO (sódico) 25 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DICLOXACILINA (sódica) 125 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'DICLOXACILINA (sódica) 500 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'DIFENHIDRAMINA (clorhidrato) 10 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'DIFENHIDRAMINA (clorhidrato) 2.5 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'DIFENHIDRAMINA (clorhidrato) 50 mg', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'DIGOXINA 0.05 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'DIGOXINA 0.25 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'DIGOXINA 0.25 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'DIMENHIDRINATO 25 mg', 'presentation' => 'Supositorio'],
            ['generic_name' => 'DIMENHIDRINATO 50 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'DOBESILATO DE CALCIO 500 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'DOBUTAMINA (clorhidrato) 12.5 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'DOPAMINA (clorhidrato) 40 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'DOXICICLINA (clorhidrato o hiclato) 100 mg', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'EFEDRINA (sulfato) 25 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'ENALAPRIL (maleato) 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ENALAPRIL (maleato) 20 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ENALAPRIL (maleato) Sinónimo(s): Enalaprilato 1.25 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'ENOXAPARINA (sódica) 40 mg (Eq 4000 UI) en 0.4 ml', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'ENOXAPARINA (sódica) 60 mg (Eq 6000 UI) en 0.6 ml', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'ERGONOVINA (maleato) Sinónimo(s): Ergometrina, Metilergonovina, Metilergometrina, Metilergobasina 0.2 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'ERITROMICINA (estearato o etilsuccinato) (no estolato) 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ERITROMICINA (etilsuccinato) (no estolato) 250 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'ERITROPOYETINA α (alfa recombinante humana) Sinónimo(s): Epoetina Alfa 2,000 UI', 'presentation' => 'Vial o Jeringa'],
            ['generic_name' => 'ERITROPOYETINA β (beta recombinante humana) Sinónimo(s): Epoetina Beta 2,000 UI', 'presentation' => 'Vial o Jeringa'],
            ['generic_name' => 'ESOMEPRAZOL 10 mg', 'presentation' => 'Sobre'],
            ['generic_name' => 'ESPIRONOLACTONA 100 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ESTREPTOQUINASA 1,500,000 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'ESTRÓGENOS CONJUGADOS 0.625 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'FACTOR DE COAGULACIÓN VIII 250 - 500 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'FENITOÍNA (sódica) Sinónimo(s): Difenilhidantoína 25 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'FENITOÍNA (sódica) Sinónimo(s): Difenilhidantoína 50 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'FENITOÍNA (sódica) Sinónimo(s): Difenilhidantoína 100 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'FENOBARBITAL 100 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'FENOBARBITAL (sódico) 130 mg / 2 ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'FENTANILO (citrato) 0.05 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'FLUCONAZOL 200 mg (2 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'FLUCONAZOL 10 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'FLUCONAZOL 200 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'FLUMAZENIL 0.1 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'FLUOROMETOLONA 0.1% (Eq 1 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'FOSFATO (sódico monobásico) + FOSFATO (sódico dibásico) 19 g + 7 g', 'presentation' => 'Frasco'],
            ['generic_name' => 'FOSFATO (sódico monobásico) + FOSFATO (sódico dibásico) 9.5 g + 3.5 g', 'presentation' => 'Frasco'],
            ['generic_name' => 'FUROSEMIDA 10 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'FUROSEMIDA 40 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'GENTAMICINA (sulfato) 40 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'GENTAMICINA (sulfato) 0.3% (Eq 3 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'GLICLAZIDA 60 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'GLUTARALDEHÍDO 2% (con activador en polvo)', 'presentation' => 'Galón'],
            ['generic_name' => 'HALOPERIDOL 5 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'HEPARINA (sódica) 5,000 UI / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'HIDRALAZINA (clorhidrato) 20 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'HIDRALAZINA (clorhidrato) 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'HIDROCLOROTIAZIDA 25 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'HIDROCORTISONA (acetato) 1% (Eq 10 mg / g)', 'presentation' => 'Tubo'],
            ['generic_name' => 'HIDROCORTISONA (succinato sódico) 100 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'HIDROCORTISONA (succinato sódico) 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'HIDRÓXIDO DE ALUMINIO + HIDRÓXIDO DE MAGNESIO (185-200 mg + 200 mg) / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'HIERRO (sacarosa) (complejo de sacarosa e hidróxido de hierro) 20 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'HIERRO (sulfato) 300 mg (Eq 60 mg de hierro elemental)', 'presentation' => 'Tableta/Gragea'],
            ['generic_name' => 'HIERRO (sulfato) 125 mg / ml (Eq 25 mg de hierro elemental)', 'presentation' => 'Frasco'],
            ['generic_name' => 'HIOSCINA (butilbromuro) Sinónimo(s): Escopolamina, Butilescopolamina 20 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'HIOSCINA (butilbromuro) Sinónimo(s): Escopolamina, Butilescopolamina 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'IBUPROFENO 100 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'IBUPROFENO 600 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'IMIPENEM (monohidrato) + CILASTATINA (sódica) 500 mg + 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'IMIPRAMINA (clorhidrato) 25 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'INMUNOGLOBULINA ANTI "D " (RH+) 0.3 mg / ml (Eq 1,500 UI)', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA ANTIHEPATITIS "B" 50 - 250 UI / ml', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA ANTIRRÁBICA 150 UI / ml', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA ANTITETÁNICA 250 UI', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'INMUNOGLOBULINA HUMANA NORMAL 5 g', 'presentation' => 'Vial'],
            ['generic_name' => 'INSULINA CRISTALINA 100 Ul / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'INSULINA ISOFÁNICA HUMANA NPH 100 UI / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'IPRATROPIO (bromuro) 250 mcg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'IPRATROPIO (bromuro) 20 mcg / aplicación', 'presentation' => 'Frasco'],
            ['generic_name' => 'IRBESARTÁN 300 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ISOSORBIDE (dinitrato) 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ISOSORBIDE (mononitrato) 20 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'KETAMINA (clorhidrato) 50 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'KETOCONAZOL 0.02', 'presentation' => 'Tubo'],
            ['generic_name' => 'LACTATO DE SODIO + ELECTROLITOS MIXTOS (Solución Hartmann o Ringer Lactato) Cada 100 ml.', 'presentation' => 'Frasco/Bolsa'],
            ['generic_name' => 'LACTULOSA 3.33 g / 5 ml (Eq 66.7 g / 100 ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'LATANOPROST 0.005% (Eq 50 mcg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'LEVODOPA + CARBIDOPA 250 mg + 25 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'LEVOFLOXACINA (hemihidrato) 750 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'LEVOFLOXACINA (hemihidrato) 500 mg (5 mg / ml)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'LEVOTIROXINA (sódica) 100 mcg', 'presentation' => 'Tableta'],
            ['generic_name' => 'LIDOCAÍNA 10% (Eq 100 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) + EPINEFRINA 2% (Eq 20 mg / ml) + 1:100,000', 'presentation' => 'Vial en cartucho'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) + EPINEFRINA (sin preservantes derivados del parabeno) 2% (Eq 20 mg / ml) + 1:200,000', 'presentation' => 'Vial'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) (con preservantes) 2% (Eq 20 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) (sin preservantes derivados del parabeno) 2% (Eq 20 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'LIDOCAÍNA (clorhidrato) (sin vasoconstrictor) 2% (Eq 20 mg / ml)', 'presentation' => 'Vial en cartucho'],
            ['generic_name' => 'LORATADINA 1 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'LORATADINA 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'LORAZEPAM 2 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'LUBRICANTE ESTÉRIL', 'presentation' => 'Tubo'],
            ['generic_name' => 'MAGNESIO (sulfato heptahidratado) 10% (Eq 100 mg / ml)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MANITOL 20% (Eq 200 mg / ml)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'MEPERIDINA (clorhidrato) Sinónimo(s): Petidina (clorhidrato) 50 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MEROPENEM 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'METFORMINA (clorhidrato) 850 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'METILCELULOSA Sinónimo(s): Hidroxipropil Metilcelulosa, Hipromelosa Carboximetilcelulosa, Carmelosa 0.5% (Eq 5 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'METILPREDNISOLONA (acetato) 0.5% (Eq 5 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'METILPREDNISOLONA (succinato sódico) 40 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'METILPREDNISOLONA (succinato sódico) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'METOCARBAMOL 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'METOCLOPRAMIDA (clorhidrato) 5 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'METOCLOPRAMIDA (clorhidrato) 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'METRONIDAZOL 500 mg (5 mg / ml)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'METRONIDAZOL 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'METRONIDAZOL 0.0075', 'presentation' => 'Tubo'],
            ['generic_name' => 'METRONIDAZOL (benzoato) 125 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'MICONAZOL 0.02', 'presentation' => 'Tubo'],
            ['generic_name' => 'MIDAZOLAM (clorhidrato) 1 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MISOPROSTOL 200 mcg', 'presentation' => 'Tableta'],
            ['generic_name' => 'MORFINA (clorhidrato o sulfato) 10 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'MOXIFLOXACINA 0.5% (Eq 5 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'MULTIVITAMINAS ADULTOS', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'MULTIVITAMINAS PEDIÁTRICAS', 'presentation' => 'Frasco'],
            ['generic_name' => 'MULTIVITAMINAS PRENATALES Cada tableta o cápsula', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'NAFAZOLINA 0.1% (Eq 1 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'NALOXONA (clorhidrato) 0.4 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'NATAMICINA 5% (Eq 50 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'NEOSTIGMINA (metilsulfato) 0.5 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'NIFEDIPINA 20 mg', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'NIFEDIPINA (liberación inmediata) 10 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'NISTATINA 100.000 UI / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'NITROFURANTOÍNA 100 mg', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'NITROGLICERINA Sinónimo(s): Trinitrato de Glicerilo 5 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'NITROPRUSIATO DE SODIO 50 mg', 'presentation' => 'Vial/Ampolla'],
            ['generic_name' => 'NORADRENALINA Sinónimo(s): Norepinefrina, Levarterenol 1 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'OCTREÓTIDA (acetato) 0.05 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'OMEPRAZOL 20 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'OMEPRAZOL 40 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'OXACILINA (sódica) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'OXIBUTININA 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'OXITETRACICLINA (clorhidrato) + POLIMIXINA B (sulfato) 5 mg / g + 10,000 UI / g', 'presentation' => 'Tubo'],
            ['generic_name' => 'OXITOCINA 10 UI', 'presentation' => 'Ampolla'],
            ['generic_name' => 'PENICILINA G BENZATÍNICA Sinónimo(s): Bencilpenicilina benzatina 1,200,000 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'PENICILINA G CRISTALINA Sinónimo(s): Bencilpenicilina o Penicilina G Sódica 1,000,000 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'PENICILINA G CRISTALINA Sinónimo(s): Bencilpenicilina o Penicilina G Sódica 10,000,000 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'PENICILINA G PROCAÍNICA Sinónimo(s): Bencilpenicilina procaína 4,000,000 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'PERMETRINA 0.01', 'presentation' => 'Frasco'],
            ['generic_name' => 'PERMETRINA 0.05', 'presentation' => 'Tubo'],
            ['generic_name' => 'PETROLATO SÓLIDO', 'presentation' => 'Tarro/Frasco'],
            ['generic_name' => 'PIPERACILINA (sódica) + TAZOBACTAM (sódico) 4 g + 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'PIRIDOXINA (clorhidrato) Sinónimo(s): Vitamina B6 50 mg', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'PIRIMETAMINA 25 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'POLIESTIRENO SULFONATO 12 - 15 g', 'presentation' => 'Sobre'],
            ['generic_name' => 'POLIMIXINA B + NEOMICINA + BACITRACINA 5000 UI + 3400 UI + 400 UI', 'presentation' => 'Tubo'],
            ['generic_name' => 'POTASIO (cloruro) 20 mEq / 10 ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'PREDNISOLONA (fosfato sódico) 15 mg / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'PREDNISONA 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'PREDNISONA 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'PROPILTIOURACILO 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'PROPOFOL (con o sin E.D.T.A.) 1% (Eq 10 mg / ml)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'PROPRANOLOL 40 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'PROTAMINA (sulfato o clorhidrato) 10 mg / ml (Eq 1,000 UI / ml)', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'RANITIDINA (clorhidrato) 25 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'Saccharomyces boulardii 200 - 250 mg', 'presentation' => 'Sobre'],
            ['generic_name' => 'SALBUTAMOL (sulfato) 100 mcg / aplicación', 'presentation' => 'Frasco'],
            ['generic_name' => 'SALBUTAMOL (sulfato) 5 mg / ml (Eq 0.5%)', 'presentation' => 'Frasco'],
            ['generic_name' => 'SALES DE REHIDRATACIÓN ORAL', 'presentation' => 'Sobre'],
            ['generic_name' => 'SALICILATO DE METILO 0.05', 'presentation' => 'Tarro'],
            ['generic_name' => 'SELEGILINA (clorhidrato) 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'SEVOFLURANO 100% V/V', 'presentation' => 'Vial'],
            ['generic_name' => 'SODIO (bicarbonato) 7.5% (Eq 0.892 mEq / ml)', 'presentation' => 'Vial/Bolsa'],
            ['generic_name' => 'SODIO (cloruro) 0.45% en envase conteniendo 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro) 0.9% en envase conteniendo 1000 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro) 0.9% en envase conteniendo 250 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro) 0.9% en envase conteniendo 100 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SODIO (cloruro) 0.9% en envase conteniendo 500 ml', 'presentation' => 'Bolsa'],
            ['generic_name' => 'SUCCINILCOLINA (cloruro) Sinónimo(s): Suxametonio (cloruro) 50 mg / ml', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'SUERO ANTIOFÍDICO (polivalente anticoral)', 'presentation' => 'Vial'],
            ['generic_name' => 'SUERO ANTIOFÍDICO (polivalente anticrotálido)', 'presentation' => 'Vial'],
            ['generic_name' => 'SULFADIAZINA 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'SULFADIAZINA DE PLATA 1% (Eq 10 mg / g)', 'presentation' => 'Tubo'],
            ['generic_name' => 'SURFACTANTE EXÓGENO PULMONAR NATURAL 25 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'TETRACAÍNA 0.5% (Eq 5 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'TIAMINA (clorhidrato) Sínónimo(s): Vitamina B1 100 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'TIAMINA (clorhidrato) Sínónimo(s): Vitamina B1 100 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'TIMOLOL (maleato) 0.5% (Eq 5 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'TIMOLOL (maleato) + DORZOLAMIDA (hidrocloruro) 5 mg / ml + 20 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'TINIDAZOL 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'TIOPENTAL (sódico) 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'TOBRAMICINA 0.3% (Eq 3 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'TRAMADOL (clorhidrato) 50 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'TRIMETOPRIM + SULFAMETOXAZOL (40 mg + 200 mg) / 5 ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'TRIMETOPRIM + SULFAMETOXAZOL 160 mg + 800 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'TROPICAMIDA 1% (Eq 10 mg / ml)', 'presentation' => 'Frasco'],
            ['generic_name' => 'VANCOMICINA (clorhidrato) 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'VERAPAMILO (clorhidrato) 240 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'VITAMINA K1 Sinónimo(s): Fitomenadiona 10 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'WARFARINA (sódica) 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'YODO + POLIVINIL PIRROLIDONA (yodo povidone) 10% + polivinil pirrolidona', 'presentation' => 'Galón/Envase'],
            ['generic_name' => 'ZINC (sulfato) 2 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'PODOFILINA (Podofilotoxina) 20 al 25%', 'presentation' => 'Frasco'],
            ['generic_name' => 'SUERO FABOTERÁPICO (polivalente antiarácnido) 6000 DL50', 'presentation' => 'Vial'],
            ['generic_name' => 'ALBENDAZOL 400 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ABIRATERONA (acetato) 250 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'APREPITANT 125 mg (1 cápsula), 80 mg (2 cápsulas)', 'presentation' => 'Set'],
            ['generic_name' => 'ASPARAGINASA Sinónimo(s): L-Asparaginase 10,000 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'AZATIOPRINA 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'BEVACIZUMAB 100 mg / 4 ml (Eq 25 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'BEVACIZUMAB 400 mg / 16 ml (Eq 25 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'BICALUTAMIDA 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'BLEOMICINA (sulfato) 15 UI', 'presentation' => 'Vial'],
            ['generic_name' => 'BORTEZOMIB 3.5 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CAPECITABINA 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CARBOPLATINO 450 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CETUXIMAB 5 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'CICLOFOSFAMIDA 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'CICLOFOSFAMIDA 200 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CICLOFOSFAMIDA 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CISPLATINO 50 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CITARABINA 100 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CITARABINA 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'CLORAMBUCILO (cloruro) 2 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'DACARBAZINA 200 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'DACTINOMICINA Sinónimo(s): Actinomicina-D 0.5 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'DOCETAXEL 20 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'DOCETAXEL 80 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'DOXORUBICINA (clorhidrato) 10 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'DOXORUBICINA (clorhidrato) 50 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'ERLOTINIB (clorhidrato) 150 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'ETOPÓSIDO Sinónimo(s): VP-16 20 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'EXEMESTANO 25 mg', 'presentation' => 'Gragea'],
            ['generic_name' => 'FACTOR DE COAGULACIÓN IX 250 - 600 UI', 'presentation' => 'Vial/Jeringa'],
            ['generic_name' => 'FACTOR DE COAGULACIÓN VIIa RECOMBINANTE Sinónimo(s): Eptacog alfa (activado), rFVIIa 1 - 5 mg (Eq 50 - 250 KUI)', 'presentation' => 'Vial'],
            ['generic_name' => 'FILGRASTIM (factor estimulador de colonias de granulocitos) 300 mcg / ml (Eq 30,000,000 UI)', 'presentation' => 'Vial o Jeringa'],
            ['generic_name' => 'FLUDARABINA (fosfato) 50 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'FLUOROURACILO Sinónimo(s): 5-FU, 5-Fluorouracilo 50 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'FOLINATO DE CALCIO Sinónimo(s): Leucovorina cálcica, ácido folínico 50 mg', 'presentation' => 'Ampolla/Vial'],
            ['generic_name' => 'GEMCITABINA 200 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'GEMCITABINA 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'GOSERELINA (acetato) 10.8 mg', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'HIDROXIUREA Sinónimo(s): Hidroxicarbamida 500 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'IFOSFAMIDA 1 g', 'presentation' => 'Vial'],
            ['generic_name' => 'INTERFERÓN BETA 1A 22 - 44 mcg', 'presentation' => 'Jeringa prellenada'],
            ['generic_name' => 'IRINOTECANO (clorhidrato) 100 mg / 5 ml (Eq 20 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'LEFLUNOMIDA 20 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'MELFALAN 2 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'MERCAPTOPURINA Sinónimo(s): 6-MP, 6-Mercaptopurina 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'MESNA Sinónimo(s): 2-mercaptoetanol sulfonato de sodio 100 mg / ml (Eq 400 mg / 4 ml)', 'presentation' => 'Ampolla'],
            ['generic_name' => 'METOTREXATO 2.5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'METOTREXATO 50 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'METOTREXATO 500 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'ONDANSETRON (clorhidrato) 2 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'OXALIPLATINO 50 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'OXALIPLATINO 100 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'OXICODONA (clorhidrato) 20 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'PACLITAXEL 30 mg / 5 ml (Eq 6 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'PACLITAXEL 150 mg / 25 ml (Eq 6 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'RITUXIMAB 100 mg / 10 ml (Eq 10 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'RITUXIMAB 500 mg / 50 ml (Eq 10 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'SOMATROPINA 5 - 12 mg', 'presentation' => 'Vial o dispositivo precargado'],
            ['generic_name' => 'TAMOXIFENO (citrato) 20 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'TEMOZOLAMIDA 100 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'TEMOZOLAMIDA 250 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'TOCILIZUMAB 80 mg / 4 ml (Eq 20 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'TOCILIZUMAB 200 mg / 10 ml (Eq 20 mg / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'TRASTUZUMAB 440 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'VINBLASTINA (sulfato) 10 mg', 'presentation' => 'Vial'],
            ['generic_name' => 'VINCRISTINA (sulfato) 1 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'VINORELBINA (bitartrato) 10 mg / ml', 'presentation' => 'Vial'],
            ['generic_name' => 'MORFINA (clorhidrato o sulfato) 30 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'MIDAZOLAM (clorhidrato) 5 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'RISPERIDONA 3 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'LITIO (carbonato) 300 mg', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'CLOZAPINA 100 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'FLUOXETINA (clorhidrato) 20 mg', 'presentation' => 'Tableta/Cápsula'],
            ['generic_name' => 'FLUFENAZINA (decanoato o enantato) 25 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'SERTRALINA (clorhidrato) 50 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'QUETIAPINA (fumarato) 300 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'BUDESONIDA + FORMOTEROL 160-200 mcg + 4.5-6 mcg', 'presentation' => 'Frasco'],
            ['generic_name' => 'CABERGOLINA 0.5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'HALOPERIDOL 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'APIXABAN 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'BUDESONIDA (Micronizada) 0.5 mg / ml', 'presentation' => 'Ampolla'],
            ['generic_name' => 'BUDESONIDA + FORMOTEROL 80 µg + 4.5 µg', 'presentation' => 'Frasco'],
            ['generic_name' => 'FUROSEMIDA 10 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'LEVETIRACETAM 500 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'LEVETIRACETAM 100 mg / ml', 'presentation' => 'Frasco'],
            ['generic_name' => 'LEVOTIROXINA 25 µg', 'presentation' => 'Tableta'],
            ['generic_name' => 'METIMAZOL (TIAMAZOL) 5 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'SODIO (cloruro) (Solución Hipertónica) 3%', 'presentation' => 'Bolsa'],
            ['generic_name' => 'GADOBUTROL 604.72 mg (Eq 1mmol de Gadobutrol, que contiene 157,25 mg de Gadolinio)', 'presentation' => 'Vial'],
            ['generic_name' => 'IOPRAMIDA 623.4 mg /ml de Iopramida (Eq 300 mg I / ml)', 'presentation' => 'Vial'],
            ['generic_name' => 'CLADRIBINA 10 mg', 'presentation' => 'Tableta'],
            ['generic_name' => 'VANCOMICINA 250 mg', 'presentation' => 'Cápsula'],
            ['generic_name' => 'PRAZIQUANTEL 600mg', 'presentation' => 'Tableta'],
        ];

        // Insertar los datos en la tabla medicines
        DB::table('medicines')->insert($medicines);
    }
}