<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MunicipalitySeeder extends Seeder
{
    public function run(): void
    {
        $municipalities = [
            // Código Departamento => [Municipios]
            1 => ['LA CEIBA','EL PORVENIR','ESPARTA','JUTIAPA','LA MASICA','SAN FRANCISCO','TELA','ARIZONA'],
            2 => ['TRUJILLO','BALFATE','IRIONA','LIMÓN','SABÁ','SANTA FE','SANTA ROSA DE AGUÁN','SONAGUERA','TOCOA','BONITO ORIENTAL'],
            3 => ['COMAYAGUA','AJUTERIQUE','EL ROSARIO','ESQUIAS','HUMUYA','LA LIBERTAD','LAMANI','LA TRINIDAD','LEJAMANÍ','MEAMBAR','MINAS DE ORO','OJOS DE AGUA','SAN JERÓNIMO','SAN JOSÉ DE COMAYAGUA','SAN JOSÉ DEL POTRERO','SAN LUIS','SAN SEBASTIAN','SIGUATEPEQUE','VILLA DE SAN ANTONIO','LAS LAJAS','TAULABE'],
            4 => ['SANTA ROSA DE COPÁN','CABAÑAS','CONCEPCIÓN','COPÁN RUINAS','CORQUÍN','CUCUYAGUA','DOLORES','DULCE NOMBRE','EL PARAÍSO','FLORIDA','LA JIGUA','LA UNION','NUEVA ARCADIA','SAN AGUSTÍN','SAN ANTONIO','SAN JERONIMO','SAN JOSÉ','SAN JUAN DE OPOA','SAN NICOLAS','SAN PEDRO','SANTA RITA','TRINIDAD DE COPÁN','VERACRUZ'],
            5 => ['SAN PEDRO SULA','CHOLOMA','OMOA','PIMIENTA','POTRERILLOS','PUERTO CORTÉS','SAN ANTONIO DE CORTÉS','SAN FRANCISCO DE YOJOA','SAN MANUEL','SANTA CRUZ DE YOJOA','VILLANUEVA','LA LIMA'],
            6 => ['CHOLUTECA','APACILAGUA','CONCEPCIÓN DE MARÍA','DUYURE','EL CORPUS','EL TRIUNFO','MARCOVIA','MOROLICA','NAMASIGUE','OROCUINA','PESPIRE','SAN ANTONIO DE FLORES','SAN ISIDRO','SAN JOSÉ','SAN MARCOS DE COLON','SANTA ANA DE YUSGUARE'],
            7 => ['YUSCARAN','ALAUCA','DANLI','EL PARAÍSO','GUINOPE','JACALEAPA','LIURE','MOROCELI','OROPOLI','POTRERILLOS','SAN ANTONIO DE FLORES','SAN LUCAS','SAN MATIAS','SOLEDAD','TEUPASENTI','TEXIGUAT','VADO ANCHO','YAUYUPE','TROJES'],
            8 => ['DISTRITO CENTRAL','ALUBAREN','CEDROS','CURAREN','EL PORVENIR','GUAIMACA','LA LIBERTAD','LA VENTA','LEPATERIQUE','MARAITA','MARALE','NUEVA ARMENIA','OJOJONA','ORICA','REITOCA','SABANAGRANDE','SAN ANTONIO DE ORIENTE','SAN BUENAVENTURA','SAN IGNACIO','SAN JUAN DE FLORES','SAN MIGUELITO','SANTA ANA','SANTA LUCIA','TALANGA','TATUMBLA','VALLE DE ÁNGELES','VILLA DE SAN FRANCISCO','VALLECILLO'],
            9 => ['PUERTO LEMPIRA','BRUS LAGUNA','AHUAS','JUAN FRANCISCO BULNES','RAMÓN VILLEDA MORALES','WAMPUSIRPI'],
            10 => ['LA ESPERANZA','CAMASCA','COLOMONCAGUA','CONCEPCIÓN','DOLORES','INTIBUCA','JESÚS DE OTORO','MAGDALENA','MASAGUARA','SAN ANTONIO','SAN ISIDRO','SAN JUAN','SAN MARCOS DE SIERRA','SAN MIGUELITO','SANTA LUCIA','YAMARANGUILA','SAN FRANCISCO DE OPALACA'],
            11 => ['ROATAN','GUANAJA','JOSÉ SANTOS GUARDIOLA','UTILA'],
            12 => ['LA PAZ','AGUANQUETERIQUE','CABANAS','CANE','CHINACLA','GUAJIQUIRO','LAUTERIQUE','MARCALA','MERCEDES DE ORIENTE','OPATORO','SAN ANTONIO DEL NORTE','SAN JOSÉ','SAN JUAN','SAN PEDRO DE TUTULE','SANTA ANA','SANTA ELENA','SANTA MARÍA','SANTIAGO DE PURINGLA','YARULA'],
            13 => ['GRACIAS','BELEN','CANDELARIA','COLOLACA','ERANDIQUE','GUALCINCE','GUARITA','LA CAMPA','LA IGUALA','LAS FLORES','LA UNION','LA VIRTUD','LEPAERA','MAPULACA','PIRAERA','SAN ANDRES','SAN FRANCISCO','SAN JUAN GUARITA','SAN MANUEL COLOHETE','SAN RAFAEL','SAN SEBASTIAN','SANTA CRUZ','TALGUA','TAMBLA','TOMALA','VALLADOLID','VIRGINIA','SAN MARCOS DE CAIQUIN'],
            14 => ['OCOTEPEQUE','BELEN GUALCHO','CONCEPCIÓN','DOLORES MERENDON','FRATERNIDAD','LA ENCARNACION','LA LABOR','LUCERNA','MERCEDES','SAN FERNANDO','SAN FRANCISCO DEL VALLE','SAN JORGE','SAN MARCOS','SANTA FE','SENSENTI','SINUAPA'],
            15 => ['JUTICALPA','CAMPAMENTO','CATACAMAS','CONCORDIA','DULCE NOMBRE DE CULMI','EL ROSARIO','ESQUIPULAS DEL NORTE','GUALACO','GUARIZAMA','GUATA','GUAYAPE','JANO','LA UNION','MANGULILE','MANTO','SALAMA','SAN ESTEBAN','SAN FRANCISCO DE BECERRA','SAN FRANCISCO DE LA PAZ','SANTA MARÍA DEL REAL','SILCA','YOCON','PATUCA'],
            16 => ['SANTA BARBARA','ARADA','ATIMA','AZACUALPA','CEGUACA','SAN JOSÉ DE COLINAS','CONCEPCIÓN DEL NORTE','CONCEPCIÓN DEL SUR','CHINDA','EL NISPERO','GUALALA','ILAMA','MACUELIZO','NARANJITO','NUEVA CELILAC','PETOA','PROTECCIÓN','QUIMISTAN','SAN FRANCISCO DE OJUERA','SAN LUIS','SAN MARCOS','SAN NICOLAS','SAN PEDRO ZACAPA','SANTA RITA','SAN VICENTE CENTENARIO','TRINIDAD','LAS VEGAS','NUEVA FRONTERA'],
            17 => ['NACAOME','ALIANZA','AMAPALA','ARAMECINA','CARIDAD','GOASCORAN','LANGUE','SAN FRANCISCO DE CORAY','SAN LORENZO'],
            18 => ['YORO','ARENAL','EL NEGRITO','EL PROGRESO','JOCON','MORAZAN','OLANCHITO','SANTA RITA','SULACO','VICTORIA','YORITO'],
        ];

        foreach ($municipalities as $code => $list) {
            $departmentId = DB::table('departments')->where('code', $code)->value('id');

            foreach ($list as $name) {
                DB::table('municipalities')->insert([
                    'name' => Str::title(Str::lower($name)),
                    'department_id' => $departmentId,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
